### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hawshemi** [sabber-slt/telegram-chatgpt-bot#4]
When you say:
```
To install all modules yarn
To run developer server yarn dev
```

What should I do? how to run `yarn`? it says:`00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.`

##

Then:
```
You can install pm2 globally before deploying. `yarn add pm2 -g`
Then run pm2 start index.js
```
But when I run `yarn add pm2 -g`, it returns: `Usage: yarn [options] yarn: error: no such option: -g`

**Comment by arfprogrammer** [comment]
you installed yarn with your OS package manager, 
please remove yarn first and execute `bash -r` command
for ensure that you have not any yarn, you can execute `whereis yarn`
then execute `npm install --global yarn`
and at last step you should ensure that your node module is minimum at 17 version
with execute `sudo n 17` command

**Comment by hawshemi** [comment]
Thanks.

`pm2` package was not installed. I installed it with `npm install --global pm2 -g`
and then `pm2 start index.js`
status is online. what's next? :|

**Comment by arfprogrammer** [comment]
please check status of service with `pm2 monitor index`
if every thing is good, helth of service is online
after that you can chat with your chat bot
you can see the log of service in ~/.pm2/log/ for error correction

**Comment by hawshemi** [comment]
Clarified with the youtube video.
https://youtu.be/_8mPpkogHKU
